title: Blog testeemail: email@email.com
author: autor
description: Um Blog teste criado a partir da ferramenta Jekyll.
#baseurl: "" # the subpath of your site, e.g. /blog
github_username: username
# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-time-machine
#show_downloads: true
plugins:
  - jekyll-feed
feed:
  categories:
    - news
